name: Deploy Spring Boot

on:
  push:
    branches:
      - main   # chạy khi push vào main

jobs:
  deploy:
    runs-on: self-hosted   # VPS Ubuntu (self-hosted runner)

    steps:
      - name: Git pull latest code
        run: |
          cd ~/charity_spring_boot/
          git reset --hard
          git pull origin main

      - name: Start/Restart Spring Boot with PM2 (Dev mode)
        run: |
          cd ~/charity_spring_boot/
          pm2 restart springboot-dev || pm2 start "mvn spring-boot:run" --name springboot-dev
