name: Deploy Spring Boot

on:
  push:
    branches:
      - main   # chạy khi push vào main

jobs:
  deploy:
    runs-on: self-hosted   # VPS Ubuntu (self-hosted runner)

    steps:
      - name: Git pull latest code
        run: |
          cd ~/charity_spring_boot/
          git fetch origin main
          git pull origin main --force

      - name: Restart Spring Boot with PM2
        shell: bash -l {0}  # 👈 quan trọng – dùng shell login để load ~/.bashrc
        run: |
          # Load nvm thủ công (phòng trường hợp shell -l vẫn chưa load hết)
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          export PATH="$HOME/.nvm/versions/node/v20.19.5/bin:$PATH"

          cd ~/charity_spring_boot/
          pm2 restart springboot-dev || pm2 start "mvn spring-boot:run" --name springboot-dev
      
