name: Deploy Spring Boot

on:
  push:
    branches:
      - main   # chạy khi push vào main

jobs:
  deploy:
    runs-on: self-hosted   # VPS Ubuntu (self-hosted runner)

    steps:
      - name: Git pull latest code
        run: |
          cd ~/charity_spring_boot/
          git reset --hard
          git pull origin main

      - name: Start/Restart Spring Boot with PM2 (Dev mode)
        run: |
          cd ~/charity_spring_boot/
          pm2 restart springboot-dev || pm2 start "mvn spring-boot:run" --name springboot-dev

      - name: Cleanup old builds (optional)
        run: |
          cd ~/charity_spring_boot/
          find target/ -type f -name "*.log" -mtime +7 -exec rm {} \;
          find target/ -type d \( \
            -name "dependency" -o \
            -name "surefire-reports" -o \
            -name "failsafe-reports" -o \
            -name "test-classes" -o \
            -name "classes" -o \
            -name "generated-sources" -o \
            -name "generated-test-sources" -o \
            -name "maven-status" -o \
            -name "maven-archiver" -o \
            -name "original" \
          \) -mtime +7 -exec rm -rf {} \;
          echo "Old build files cleaned up."
